### PR TITLE
Actually check status code of rustdoc (--test) command

### PR DESCRIPTION
**Pull request by JelteF**
Right now the doctests are being run, but the output is not shown and the exit code is ignored.
This changes the code to check the status code and show the output if it's non-zero. It will also exit cargo-external-doc in this case.

Apart from this there are two other changes:
- The PR also runs `rustfmt` on the source code
- A Cargo.lock file is added for reproducibility

### CODE REVIEW

**Comment by JelteF** [comment]
I tried this out on the `nom` repo and some of the doctests actually fail.

**Comment by JelteF** [comment]
Any reason why this cannot be merged?

**Comment by JelteF** [comment]
@Geal Bumping this once more.

**Comment by Geal** [comment]
thanks, sorry for the delay

**Comment by Geal** [comment]
I published a 0.2

**Comment by JelteF** [comment]
Awesome!

**Pull request merged**
